services:
  react:
    container_name: react
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      WATCHPACK_POLLING: "true"
    ports: 
      - 3000:3000
    volumes:
      - ./client:/usr/src/client/
    networks:
      - mern-net

  express:
    container_name: express
    build:
      context: ./server
      dockerfile: ./Dockerfile
      args:
        - ./config.env
    command: nodemon -L server.js
    volumes:
      - ./server:/usr/src/server/
    ports:
      - 5000:5000
    networks:
      - mern-net

networks:
  mern-net:
    driver: "bridge"
    