name: Run Tests

on:
  push:
    branches: [main]
    paths:
      - "/"
  workflow_dispatch:

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  
  #     - name: Build the Docker image
  #       run: |
  #         docker-compose build mern-api mern-react   
          
  #     - name: Docker List Images # For tracking only, make sure they're up.
  #       run: |
  #         docker image ls
  
  api-test:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Install jq (json parser)
        working-directory: ./server
        run: |
          sudo apt-get install jq
          
      - name: Install dependencies
        working-directory: ./server
        run: |
          npm install

      - name: Run test command
        working-directory: ./server
        run: |
          npm test --json > testResults
      
      - name: sed line with json -> pipe to jq for success boolean
        id: get_result
        working-directory: ./server
        run: |
          echo ::set-output name=success::$(sed -n 5p testResults | jq '.success')
          
      - name: Only pass if success is true
        working-directory: ./server
        run: |
          if [[ ${{ steps.get_result.outputs.success }} == true ]]; then exit 0; else exit 1; fi
          

